#define MAX_RACE_MAPS 500
#define MAX_RACE_CHACKS 50
#define MAX_RACE_RANKS 10

#define RACE_MAP_MAKE 0
#define RACE_MAP_FINISH 1
#define RACE_MAP_EDIT 2

#define MAX_RACE_ROOM MAX_RACE_MAPS

#define RACE_ROOM_WAIT 0
#define RACE_ROOM_START 1
#define RACE_ROOM_FINISH 2

